name: "Workflow"

on:
  push:
    branches: [ "main" ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - name: "Setup flyctl"
        uses: "superfly/flyctl-actions/setup-flyctl@master"

      - name: "Deploy"
        run: "flyctl deploy --remote-only"